site_name: sparse_grid
site_description: A Python Sparse Grid Package
site_url: https://eggzec.github.io/sparse_grid/
repo_url: https://github.com/eggzec/sparse_grid
repo_name: eggzec/sparse_grid

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eggzec/sparse_grid
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/sparse_grid/

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - tables
  - fenced_code
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Theory: theory.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - API Reference: api.md
  - References: references.md
